# -*- coding: utf-8 -*-
"""TP PPI BONINI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fDAcCHxBYGqw_4f6t-QyKHbuXsfqHst
"""

# Commented out IPython magic to ensure Python compatibility.
# Instalar Pillow
# %pip install Pillow

import os
from PIL import Image

"""### Definición de Parámetros y Directorios

Aquí puedes configurar las carpetas de entrada y salida, el tamaño deseado para las imágenes, y la ruta de tu logo para la marca de agua. Asegúrate de que las carpetas existan y que la ruta al logo sea correcta.
"""

# --- Parámetros de Configuración ---
INPUT_FOLDER = '/content/sample_data/input'
OUTPUT_FOLDER = '/content/sample_data/output'
LOGO_PATH = '/content/sample_data/mark/logo.jpg' # Asegúrate de que este archivo exista

TARGET_SIZE = (500, 500) # Tamaño máximo para el redimensionamiento (ancho, alto)
WATERMARK_SIZE_PERCENT = 0.15 # Porcentaje del tamaño de la imagen para el logo (ej. 0.15 = 15%)
WATERMARK_POSITION = 'bottom_right' # Puede ser 'top_left', 'top_right', 'bottom_left', 'bottom_right'
WATERMARK_OPACITY = 0.6 # Opacidad del logo (0.0 a 1.0)

"""### Función de Redimensionamiento Inteligente

Esta función redimensionará la imagen para que se ajuste a las dimensiones `TARGET_SIZE` manteniendo su relación de aspecto, de modo que la imagen no se distorsione.
"""

def resize_and_crop(image: Image.Image, target_size: tuple) -> Image.Image:
    """Redimensiona una imagen para que llene el target_size y luego la recorta desde el centro.
    Esto asegura que la imagen final sea del tamaño exacto y mantenga la proporción."""
    original_width, original_height = image.size
    target_width, target_height = target_size

    original_aspect = original_width / original_height
    target_aspect = target_width / target_height

    if original_aspect > target_aspect:
        # La imagen original es más ancha que la proporción objetivo, escalar por altura
        scale_ratio = target_height / original_height
        resize_width = int(original_width * scale_ratio)
        resize_height = target_height
    else:
        # La imagen original es más alta o tiene la misma proporción, escalar por ancho
        scale_ratio = target_width / original_width
        resize_width = target_width
        resize_height = int(original_height * scale_ratio)

    # Redimensionar la imagen para que al menos cubra las dimensiones objetivo
    scaled_image = image.resize((resize_width, resize_height), Image.Resampling.LANCZOS)

    # Calcular las coordenadas de recorte desde el centro
    left = (resize_width - target_width) / 2
    top = (resize_height - target_height) / 2
    right = (resize_width + target_width) / 2
    bottom = (resize_height + target_height) / 2

    # Recortar la imagen
    cropped_image = scaled_image.crop((left, top, right, bottom))

    return cropped_image

"""### Función para Aplicar Marca de Agua

Esta función superpondrá tu logo en una esquina específica de la imagen, con la opacidad y el tamaño que definiste.
"""

def apply_watermark(image: Image.Image, logo_path: str, position: str, size_percent: float, opacity: float) -> Image.Image:
    """Aplica una marca de agua (logo) a una imagen."""
    try:
        logo = Image.open(logo_path).convert("RGBA")
    except FileNotFoundError:
        print(f"Error: El archivo del logo '{logo_path}' no fue encontrado. Saltando marca de agua.")
        return image
    except Exception as e:
        print(f"Error al cargar el logo '{logo_path}': {e}. Saltando marca de agua.")
        return image

    img_width, img_height = image.size
    logo_width, logo_height = logo.size

    # Calcular el tamaño del logo basado en el porcentaje de la imagen
    target_logo_width = int(img_width * size_percent)
    if target_logo_width == 0: # Evitar tamaño cero si la imagen es muy pequeña
        target_logo_width = 1
    target_logo_height = int(logo_height * (target_logo_width / logo_width))
    if target_logo_height == 0:
        target_logo_height = 1

    logo = logo.resize((target_logo_width, target_logo_height), Image.Resampling.LANCZOS)

    # Ajustar la opacidad del logo
    alpha = logo.split()[3]
    alpha = alpha.point(lambda p: p * opacity)
    logo.putalpha(alpha)

    # Definir la posición del logo
    padding = int(img_width * 0.02) # Un pequeño margen
    if position == 'top_left':
        x, y = padding, padding
    elif position == 'top_right':
        x, y = img_width - logo.width - padding, padding
    elif position == 'bottom_left':
        x, y = padding, img_height - logo.height - padding
    elif position == 'bottom_right':
        x, y = img_width - logo.width - padding, img_height - logo.height - padding
    else:
        print("Posición de marca de agua no válida. Usando 'bottom_right'.")
        x, y = img_width - logo.width - padding, img_height - logo.height - padding

    # Crear una copia de la imagen para no modificar la original directamente al pegar
    watermarked_image = image.copy()
    if watermarked_image.mode != 'RGBA':
        watermarked_image = watermarked_image.convert('RGBA')

    watermarked_image.alpha_composite(logo, (x, y))
    return watermarked_image

"""### Función Principal de Procesamiento

Esta es la función que orquesta todas las tareas:
1.  Lee cada imagen de la carpeta de entrada.
2.  Normaliza su perfil de color a RGB.
3.  Redimensiona la imagen de forma inteligente.
4.  Aplica la marca de agua.
5.  Convierte la imagen al formato `.webp` y la guarda en la carpeta de salida.
"""

def process_images(
    input_folder: str,
    output_folder: str,
    logo_path: str,
    target_size: tuple,
    watermark_size_percent: float,
    watermark_position: str,
    watermark_opacity: float
) -> None:
    """Procesa todas las imágenes en una carpeta: redimensiona, aplica marca de agua y convierte a WebP."""
    print(f"Iniciando procesamiento de imágenes desde '{input_folder}'...")
    for filename in os.listdir(input_folder):
        if filename.lower().endswith(('.png', '.tiff', '.jpg', '.jpeg')):
            input_path = os.path.join(input_folder, filename)
            base_name = os.path.splitext(filename)[0]
            output_path = os.path.join(output_folder, f'{base_name}.webp')

            try:
                with Image.open(input_path) as img:
                    print(f"Procesando: {filename}")

                    # 1. Normalización de perfil de color a RGB
                    # Convertir a RGBA primero para manejar transparencias, luego a RGB si no es necesario Alpha
                    if img.mode != 'RGBA':
                        img = img.convert('RGBA')

                    # Si la imagen original no tenía canal alpha o no queremos preservarlo, podemos convertir a RGB
                    # Aunque para webp, RGBA es generalmente preferible si hay transparencia
                    # Para asegurar que sea RGB para compatibilidad, convertimos de RGBA a RGB si es el caso
                    # Aquí la mantendremos en RGBA si es posible para un mejor WebP con transparencia

                    # 2. Redimensionado y recorte inteligente para llenar el TARGET_SIZE
                    processed_img = resize_and_crop(img, target_size)

                    # 3. Marca de agua
                    watermarked_img = apply_watermark(
                        processed_img,
                        logo_path,
                        watermark_position,
                        watermark_size_percent,
                        watermark_opacity
                    )

                    # Convertir a RGB si la marca de agua hizo que fuera RGBA y no se quiere transparencia en el final .webp
                    # Sin embargo, WebP soporta transparencia, por lo que RGBA es a menudo lo ideal.
                    # Si el objetivo final es un JPEG (sin transparencia), se convertiría a RGB aquí.
                    # Para WebP con posible transparencia, mantendremos RGBA si la imagen o el logo la tienen.
                    if watermarked_img.mode != 'RGB':
                         watermarked_img = watermarked_img.convert('RGB') # Forzamos RGB si WebP no debe tener transparencia

                    # 4. Conversión a .webp y guardado
                    watermarked_img.save(output_path, 'webp', quality=85) # Ajusta la calidad (0-100)
                    print(f"Guardado: {output_path}")

            except Exception as e:
                print(f"Error al procesar '{filename}': {e}")

    print("Procesamiento de imágenes completado.")

"""### Ejecutar el Procesamiento

Finalmente, ejecuta la función principal con los parámetros que definiste. Asegúrate de haber colocado tus imágenes originales en la carpeta especificada por `INPUT_FOLDER` y tu logo en la ruta especificada por `LOGO_PATH`.
"""

# Llamar a la función principal para procesar las imágenes
process_images(
    input_folder=INPUT_FOLDER,
    output_folder=OUTPUT_FOLDER,
    logo_path=LOGO_PATH,
    target_size=TARGET_SIZE,
    watermark_size_percent=WATERMARK_SIZE_PERCENT,
    watermark_position=WATERMARK_POSITION,
    watermark_opacity=WATERMARK_OPACITY
)

from IPython.display import display
from PIL import Image

image_path = "/content/sample_data/output/fruta2.webp"

try:
    img_to_display = Image.open(image_path)
    display(img_to_display)
except FileNotFoundError:
    print(f"Error: La imagen en la ruta '{image_path}' no fue encontrada.")
except Exception as e:
    print(f"Ocurrió un error al cargar o mostrar la imagen: {e}")

